cache_table: false
crossover_prob: 0.8
attribute: Porosity
elitism_prob: 0.01
fitness_function: R^2
generations: 50
image_based: true
initial_max_depth: 7
initial_min_depth: 4
maxDepth: 9
mutation_prob: 0.2
mut_eph_prob: 0.25
pop_size: 512
tournament_size: 4
save_tree: true